version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./build:/usr/share/nginx/html
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
