version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./build:/usr/share/nginx/html
    ports:
      - '3002:80'
  nginx:
    depends_on:
      - web
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '5000:80'
